{"name": "test_login01[2-4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (2 + 4) == 2", "trace": "self = <test_case.testfunc01.TestLogin object at 0x000001E03FEEB280>, a = 2\nb = 4\n\n    @pytest.mark.parametrize('a,b', [(1, 1), (2, 4), (2, 6), (6, 7)])\n    def test_login01(self, a, b):\n        print('---test_login01---')\n>       assert a + b == 2\nE       assert (2 + 4) == 2\n\ntestfunc01.py:13: AssertionError"}, "parameters": [{"name": "a", "value": "2"}, {"name": "b", "value": "4"}], "start": 1622897684654, "stop": 1622897684655, "uuid": "05db10c3-67e6-4346-959f-5bb507e7bcef", "historyId": "e8800e043aaac13fb73526b86cf461d2", "testCaseId": "6476584284445ea88e6a99052c533646", "fullName": "test_case.testfunc01.TestLogin#test_login01", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "testfunc01"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-BFADA0J"}, {"name": "thread", "value": "13612-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.testfunc01"}]}